#define _EOI_					0
#define ACTION				1
#define CODE_BLOCK		2
#define COLON					3
#define FIELD					4
#define LEFT					5
#define NAME					6
#define NONASSOC			7
#define OR						8
#define PREC 					9
#define RIGHT					10
#define SEMI					11
#define SEPARATOR  		12
#define START					13
#define TERM_SPEC			14
#define TYPE					15
#define PERCENT_UNION 16
#define WHITESPACE		17