#define _EOI_   0
#define ACTION     1
#define CODE_BLOCK 2
#define COLON      3
#define FIELD      4
#define LEFT       5
#define NAME       6
#define NONASSOC   7
#define OR         8
#define OTHER      9
#define PREC       10
#define RIGHT      11
#define SEMI       12
#define SEPARATOR  13
#define TERM_SPEC  14
#define TYPE       15
#define PERCENT_UNION 16
#define WHITESPACE 17
